version: '3'
services:
  wcfsampleservice:
    build:
      context: .
      dockerfile: .\WcfSampleService\Dockerfile
    ports:
      - "5000:80"

  aspnetframworkvbwebform:
    build:
      context: .
      dockerfile: .\AspNetFramworkVBWebForm\Dockerfile
    ports:
      - "8000:80"
    depends_on: 
      - wcfsampleservice

