'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization

Namespace WcfSampleService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/WcfSampleService")>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private BoolValueField As Boolean
        
        Private StringValueField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                Me.BoolValueField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                Me.StringValueField = value
            End Set
        End Property
    End Class
End Namespace


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IService1")>  _
Public Interface IService1
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
    Function GetData(ByVal value As Integer) As String
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
    Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
    Function GetDataUsingDataContract(ByVal composite As WcfSampleService.CompositeType) As WcfSampleService.CompositeType
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
    Function GetDataUsingDataContractAsync(ByVal composite As WcfSampleService.CompositeType) As System.Threading.Tasks.Task(Of WcfSampleService.CompositeType)
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface IService1Channel
    Inherits IService1, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class Service1Client
    Inherits System.ServiceModel.ClientBase(Of IService1)
    Implements IService1
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Function GetData(ByVal value As Integer) As String Implements IService1.GetData
        Return MyBase.Channel.GetData(value)
    End Function
    
    Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements IService1.GetDataAsync
        Return MyBase.Channel.GetDataAsync(value)
    End Function
    
    Public Function GetDataUsingDataContract(ByVal composite As WcfSampleService.CompositeType) As WcfSampleService.CompositeType Implements IService1.GetDataUsingDataContract
        Return MyBase.Channel.GetDataUsingDataContract(composite)
    End Function
    
    Public Function GetDataUsingDataContractAsync(ByVal composite As WcfSampleService.CompositeType) As System.Threading.Tasks.Task(Of WcfSampleService.CompositeType) Implements IService1.GetDataUsingDataContractAsync
        Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
    End Function
End Class
